language: node_js
before_script:
  - npm install -g gatsby-cli
node_js:
  - '12'
deploy:
  provider: script
  script: yarn install && yarn run deploy
  skip_cleanup: true
  on:
    branch: master
notifications:
  slack:
    secure: KcnHyL+AOfp49vCOhrlOkf1FspH5XT8Gw0bsJEetOQrN5PWZSRdY31ZEJwrhkEz+8WIWPoT4XbyJutSVfBVFZRCv3/BdmqLVbqOIaEzNEbODNbKPZOsIrvBrT/mr1gCUOFdvakepQvb6PTs0w0WuO5Q5AqqFTKxMyhvMEnBvMFvV7zR5H4XuI9DQuxA6MQetj8SnVMGMNBYk+q/muGlrhJQfCnL0iQgLSlPFyVtYqaXiyOIppQVYfxpEtFuZd6eR6sR1/ooy4S+yU5E7iZyAMua+wWmv9wCkF8A0FqUtl870E8TBLO7idZlEqhmuALLxV4jEyXr1jt2dgGwOAZgJvEgOu5jKNUnQRJwhvkKWiPusQWfqP6HWLqhgKPYk9KUD1/i+85oYb+D/GNlIZpm6RQFMkbAWnbTBtw3byRVL4EcTyK+VZg9u89u3uvacDVIq7ByXHTzcJDiZprFPSDAHnNmhIq6CY4k+OyZvEAHXe2n+yxqOJ1VQrl4tH1x50PdNEZGlFIAppz/srSKcIGR5DqmtuWptT1DkdtujT+8mWQEp57BwL8CrRA6xWmAjW4lQXyewWLUy8qCS9kAMaK7eslUbCn4kMhqBWc1w+bD43v3XZrasdDYV6RVtGRpvI38sTtvXUcB2f/FLG/rkWYTh/4/0ycLxuu54elX1njO/0d4=
